name: bigdataafrica_docker_ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd server && docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica .
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: whoami && cd ${{ secrets.PROJECT_PATH }} && docker container stop $(docker container ls -q --filter name=thebigdataafrica*) && docker rm -v $(docker ps -aq -f name=thebigdataafrica*) && docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica && docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest && docker run --restart=always -it --name thebigdataafrica -e MONGO_URI="${{ secrets.MONGO_URI }}" -e PORT="${{ secrets.PORT }}" -e JWT_SECRET="{{ secrets.JWT_SECRET }}" -e SALT_ROUNDS="{{ secrets.SALT_ROUNDS }}" -p 127.0.0.1:${{ secrets.PORT }}:${{ secrets.PORT }} -d ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest && docker network connect thebigdataafrica_network thebigdataafrica
      # - run: docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica # remove outdated image
      # - run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest # pull latest image
      # - run: docker run -it --rm --name thebigdataafrica -p ${{ secrets.PORT }}:${{ secrets.PORT }} -d ${{ secrets.DOCKER_HUB_USERNAME }}/thebigdataafrica:latest # run updated container
      # - run: docker ps -a # verify the update
