version: '3.9'

services:
  reverse:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/custom-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/custom-nginx/certs:/etc/ssl/private
